Wrappers task
andrewVolodko/TestRailTestFramework pull request #1
Opened 2021-04-24 20:49 UTC by andrewVolodko

Обертки для Checkbox, RadioButton и DropdownMenu

2021-05-17 19:40 UTC, wildpioneer requested changes

2021-05-17 19:40 UTC, wildpioneer commented on src/main/java/wrappers/Checkbox.java
> +    public void changeState(boolean makeSelected) {
Я бы не делал такой сложный метод, а лучше два понятных: tick и untick - и без параметров.

2021-05-17 19:40 UTC, wildpioneer commented on src/main/java/wrappers/DropdownMenu.java
> +    public DropdownMenu(BrowserService browserService, By dropdownMenuDivElBy) {
Тут бы я добавил описание конструктора
    /**
     * 
     * @param browserService
     * @param dropdownMenuDivElBy
     */
В котором прописал бы - как именно надо искать селектор для DropDownMenu

2021-05-17 19:40 UTC, wildpioneer commented on src/main/java/wrappers/SelectWithDropdown.java
> +public class SelectWithDropdown {
Название Wrapper-а не очень понятное

2021-05-17 19:40 UTC, wildpioneer commented on src/main/java/models/SelectWithDropdownContainer.java
> +public class SelectWithDropdownContainer {
А почему этот класс храниться в моделях - он же не относиться к моделям приложения.

2021-05-23 14:46 UTC, andrewVolodko commented on src/main/java/wrappers/Checkbox.java
> +    public void changeState(boolean makeSelected) {
Done.

2021-05-23 14:46 UTC, andrewVolodko commented on src/main/java/wrappers/DropdownMenu.java
> +    public DropdownMenu(BrowserService browserService, By dropdownMenuDivElBy) {
Done.

2021-05-23 14:46 UTC, andrewVolodko commented on src/main/java/wrappers/SelectWithDropdown.java
> +public class SelectWithDropdown {
Обсудили на лекции. Это название именно с самого сайта.

2021-05-23 14:47 UTC, andrewVolodko commented on src/main/java/models/SelectWithDropdownContainer.java
> +public class SelectWithDropdownContainer {
Создал пакет containers в пакете models, перенес туда подобные классы.

2021-06-06 08:10 UTC, merged